name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@v2
      with:
        version: 7.16.1
        
    - name: Setup Node.js 17.1.0
      uses: actions/setup-node@v3
      with:
        node-version: 17.1.0
        cache: 'pnpm'
        
    - run: pnpm install
    
    - run: pnpm run build
